

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:http://localhost:8088"
  spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

