spring:
  application:
    name: notifi-service
  config:
    import: "optional:configserver:http://localhost:8088"
  mail:
    host: smtp.gmail.com
    port: 587
    username: phucnddevptit@gmail.com
    password: mklu owph mtei qozy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true